### ISSUE TITLE
Using subscribe does not seem to open a websocket

### ISSUE THREAD

**Issue by Zvax** [timhall/svelte-apollo#10]
Hello!

I am trying to use the subscribe function, but it would seem that the subscription creates a single http request and not the websocket I think should be seen.

I have created a branch [here](https://github.com/crim-ca/svelte-apollo/tree/test-subscribe) with some code that reproduces the behaviour. 

From that branch, when using the playground, we can create the following subscription, activate it and then observe the payloads being delivered in the playground. Looking at the network tab of the inspector, there's a websocket through which the data is being transferred.

However, when running the example (I added a naive section with the payloads) I can only see a single http request that promptly closes and subsequently does not receive the payloads. Am I correctly using the code? Is it possible there's a binding with Apollo's subscription that does not go through?

The subscribe test does run correctly in the environment where that happens. The subscription query being used in the playground and the example:

```
subscription ListenChange {
    foo_changed
}
```

Cheers, and thank you for this project!

**Comment by timhall** [comment]
Hmm, looks like websockets are [not included in apollo-boost](https://github.com/apollographql/apollo-client/issues/3117). If you can't get it working with [apollo-link-ws](https://www.npmjs.com/package/apollo-link-ws), please let me know.

**Comment by jesperordrup** [comment]
I have same problem - or at least .. my subscriptions didnt work result was null and never updated. I tried the above and ran into some problems.

During compile I get this error:
Error: "Subcription is not exported by node_modules/subscriptions-transport-ws/dist/index.js"

This I think I fixed with: 
https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports

```
		commonjs({
			namedExports: {
				// left-hand side can be an absolute path, a path
				// relative to the current directory, or the name
				// of a module in node_modules
				'./node_modules/subscriptions-transport-ws/dist/index.js': ['SubscriptionClient']
			}
		}),
```

Now it compiles but when I open site chrome says:
"Uncaught ReferenceError: events is not defined" in main.js


My component:
```
<script>
  import { getClient, subscribe } from 'svelte-apollo';
  import { SubscriptionClient } from "subscriptions-transport-ws";
  import { WebSocketLink } from "apollo-link-ws";
  import { CLIENT_SUBSCRIBE } from './data';
  import Showit from './Showit.html';
  const client = new SubscriptionClient("http://localhost:4000/graphql/", {
    reconnect: true
  });
  const link = new WebSocketLink(client);

  const new_books = subscribe(client, { query: CLIENT_SUBSCRIBE });
</script>

{#await $new_books}
    Waiting for new client...
  {:then result}
    New client: 
    <Showit model={result}/>
  {/await}
```

Showit.html

```
<script>
    export let model;
    console.log(model);
</script>
<div>
    <pre>{model}</pre>
</div>

```

**Comment by frederikhors** [comment]
@jesperordrup me too. I created this: https://github.com/timhall/svelte-apollo/issues/13

**Comment by frederikhors** [comment]
@jesperordrup I created a simple repo: https://codesandbox.io/s/zn1mnon8jl.

If you open it in codesandbox it works! But if you download as a zip and execute npm i && npm run dev you can see the problem.

**Comment by frederikhors** [comment]
I opened a SO question to recap the problem: https://stackoverflow.com/questions/56167898/rollup-and-subscriptions-transport-ws

@timhall can you help me?

**Comment by salahazek** [comment]
@frederikhors facing same issue. Any fix ?
