### ISSUE TITLE
Support for graphql 16.x

### ISSUE THREAD

**Issue by lucasnad27** [timhall/svelte-apollo#113]
The `graphql` library released v16.0 back in October. Here's a list of [breaking changes & features](https://github.com/graphql/graphql-js/releases/tag/v16.0.0). This isn't holding me back from using this library but would be nice to support the latest version.

By no means am I a javascript expert, but if there is adequate demand to make this update, I can look through this libraries' usage of `graphql` and look for any breaking changes and get a PR going.

**Comment by timhall** [comment]
Resolved in v0.5.0
