### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by MonaMayrhofer** [timhall/svelte-apollo#115]
Please excuse my ignorance if I overlooked something obvious, but this repository seems to be rather stale/unmaintained.

Yet I believe that the library is still used by many, so I want to clarify if this project is safe to use.

Is this still the way to go when trying to incorporate Apollo with Svelte? 
Are there plans to improve the documentation?
Are there security/compatibility concerns when using this project?

**Comment by michaelwooley** [comment]
Not a maintainer but I believe the answer is **YES**. Last PR was 14 days ago: https://github.com/timhall/svelte-apollo/pull/117

**Comment by MonaMayrhofer** [comment]
Perfect
