### ISSUE TITLE
'process.env.NODE_ENV': JSON.stringify('development'). Why?

### ISSUE THREAD

**Issue by frederikhors** [timhall/svelte-apollo#12]
Can you explain these lines in `rollup.config.js` please?

```js
replace({
  'process.env.NODE_ENV': JSON.stringify('development')
})
```

**Comment by timhall** [comment]
Apollo depends on `process.env.NODE_ENV` being set and I chose `"development"` for the example so that any warnings/errors were a little more verbose. Feel free to set that to production in your code or pull it from the environment.
