### ISSUE TITLE
Subcription is not exported by node_modules/subscriptions-transport-ws/dist/index.js

### ISSUE THREAD

**Issue by frederikhors** [timhall/svelte-apollo#13]
I'm using https://github.com/sveltejs/template with rollup (https://github.com/sveltejs/template/blob/master/rollup.config.js).

During compile I get this error:
Error: "Subcription is not exported by node_modules/subscriptions-transport-ws/dist/index.js"

This I think I fixed with: 
https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports

```
commonjs({
	namedExports: {
		'./node_modules/subscriptions-transport-ws/dist/index.js': ['SubscriptionClient']
	}
}),
```

Now it compiles but when I open site chrome says:
"Uncaught ReferenceError: events is not defined" in main.js

I created a simple repo: https://codesandbox.io/s/zn1mnon8jl.

If you open it in codesandbox it works! But if you download as a zip and execute `npm i && npm run dev` you can see the problem.

_Originally posted by @jesperordrup in https://github.com/timhall/svelte-apollo/issues/10#issuecomment-491517274_

Rollup hates us novices.

**Is SubscriptionClient correctly exported and correctly imported in apollo-link-ws?**

@timhall can you take an hint? I can create a PR with a more advanced example using SUBSCRIPTIONS.

**Comment by frederikhors** [comment]
@JoviDeCroock suggested something that I haven't understood yet, here: https://github.com/apollographql/apollo-link/issues/1043.

**Comment by praveenweb** [comment]
@frederikhors - I have a sample app working with GraphQL subscriptions here - https://github.com/hasura/graphql-engine/tree/master/community/sample-apps/svelte-apollo
It uses a slightly modified rollup config with `rollup-plugin-node-resolve` plugin to make it work.

**Comment by frederikhors** [comment]
@praveenweb amazing. It builds. Thanks.
