### ISSUE TITLE
"'watchQuery' of undefined" error using a routing solution. Maybe we need to wait "setClient(client)"?

### ISSUE THREAD

**Issue by frederikhors** [timhall/svelte-apollo#16]
I think I found a bug.

I still don't know if the bug is caused by `svelte-apollo` or what I'm using for routing in this project: `svero` (https://github.com/kazzkiq/svero).

**PROBLEM REPRODUCTION**: https://codesandbox.io/s/bzix3

In codesandbox there are still some problems with Svelte (or maybe I'm the problem) but it doesn't work. You have to download it and run with: `npm i && npm run dev`.

**THE PROBLEM**:

If I go to `http://localhost:5000/` the Home Page is correctly displayed.

If I go to `http://localhost:5000/articles` **USING THE LINK!!!** the Articles Page is correctly displayed.

If now I reload the page I get this error in browser console:

```log
svelte-apollo.es.js:51 Uncaught TypeError: Cannot read property 'watchQuery' of undefined
    at query (svelte-apollo.es.js:51)
    at instance$3 (ArticlesPage.svelte:14)
    at init (internal.mjs:1395)
    at new ArticlesPage (ArticlesPage.svelte:14)
    at updateComponent (Router.svelte:24)
    at handleRoute (Router.svelte:65)
    at Router.svelte:76
    at Array.some (<anonymous>)
    at handlePopState (Router.svelte:70)
```

If I use `console.log(client)` just after `ArticlesPage.svelte` line 13 (`const client = getClient();`) I can see the client is indeed `undefined`.

Maybe we have to wait for `setClient(client)` in the `App.svelte` file to finish is job?

**Comment by frederikhors** [comment]
@timhall sorry for this ping. Some idea?

**Comment by timhall** [comment]
After digging through the svero code I think the issue is that it renders components with `new Component` which does not pass context down to the child routes. I’m not quite sure how it works on navigate, but not refresh, but I think that’s the issue. 

You’ll have to put your client instance in a shared module that is imported into each route rather than use `setClient` and `getClient` (which use context). 

```html
<script>
import { query } from 'svelte-apollo';
import client from './data/client';

const result = query(client, /* ... */);
</script>
```

**Comment by frederikhors** [comment]
@timhall, thanks four your answer. I did not understand what you mean, but if I use something like this it works:

```js
  let isLoaded = false;
  onMount(() => {
    setTimeout(() => {
      isLoaded = true;
    });
  });

{#if isLoaded}
  <Router>
    ...
</Router>
{/if}
```

But as you know it's an hack!

**Comment by frederikhors** [comment]
For performance loss is better a context solution or a reference one?

Is it ok to use `import client from './data/client';` everywhere instead of the context way?

In essence, what does it actually change for the purposes of `svelte-apollo`?
