### ISSUE TITLE
Context solution or client reference (import) one

### ISSUE THREAD

**Issue by frederikhors** [timhall/svelte-apollo#18]
_Issue opened for the creation of a wiki page that summarizes the doubts and problems for newbies (if you agree)._

Coming from issue https://github.com/timhall/svelte-apollo/issues/16 I'm wondering if - for a performance POV - is better to use:

- `setClient()` and `getClient()` or

- `import client from './data/client'` everywhere in my components (instead of `getClient()`).

In essence, what does it actually change for the purposes of `svelte-apollo`?

**Is the Apollo cache in some way not the same cache?**

_I'm really newbie in browser progamming and in Svelte. Sorry for the silly question and thanks for your amazing work._

**Comment by frederikhors** [comment]
@timhall can you answer this please?

**Comment by justinmoon** [comment]
@frederikhors: I'm no expert either, but it seems that multiple `ApolloClient` instances will each have independent caches. Using `setClient` and `getClient` allow everything to just share 1 `ApolloClient` and 1 cache.

**Comment by thojanssens** [comment]
@justinmoon The same ES6 module is evaluated just once. So there will be no multiple `ApolloClient` instances. ES6 imports should therefore work just fine.

See here the advantages of using a Context:
https://spectrum.chat/apollo/general/why-use-a-provider-or-context-for-the-client-instead-of-simply-importing-a-file~757174e0-36a6-4f0e-998e-8a7325dd61fc

**Comment by thojanssens** [comment]
@frederikhors @justinmoon 
But can I ask you a quick question? Why are the queries not executed in a `onMount` lifecycle? Usually we do our fetch operations in `onMount`, right? In the example there is no usage of it.
