### ISSUE TITLE
Rerender just an item in list, not all the list items.

### ISSUE THREAD

**Issue by frederikhors** [timhall/svelte-apollo#19]
I have a big list of items.

Everything works good. But.

Everytime I update an item the big list re-render itself.

### REPRODUCTION:
- https://codesandbox.io/s/romantic-brattain-znnzd
- _If you click on a button the mutation re-render all the items instead of the single item._
- I'm already using `<svelte:options immutable/>` in `Button.svelte`

---

Maybe this is related to this example in Svelte tutorial https://svelte.dev/tutorial/svelte-options?

Have you already had this problem? @timhall @jacwright @lukeed

**Comment by frederikhors** [comment]
@timhall Issue edited.

**Comment by sergelerner** [comment]
@frederikhors I'm trying to understand the same thing. Wondering if you learned anything since?

**Comment by lukeed** [comment]
Sorry, no experience here. Don't use Apollo/GraphQL at all

**Comment by frederikhors** [comment]
@sergelerner not much. Can you answer today?

**Comment by Momics** [comment]
I just had a similar issue. I figured it is because of the #await block. Just before updating the store the promise is 'reset'. This results in the entire each loop being rerendered. I am not sure if this is intended behaviour.

I fixed it by awaiting the promise in between the script tags like so:

`
<script>
  import { getClient, query } from "svelte-apollo";

  const client = getClient();
  const data = query(client, {
    query: SOME_QUERY,
  });

  let resultData = []
  $: $data.then(data => resultData = data.data.queryResult)
  
</script>

{#each resultData as d (d._id)}
  <div>{d}</div>>
{/each}
`

I don't think this is an elegant solution, but it works for me.

**Comment by frederikhors** [comment]
@timhall Is this something we can fix?

**Comment by cdock1029** [comment]
If you add this in `Button.svelte`

```js
onDestroy(() => {
  console.log("destroyed", player.id);
});
```
or this in `App.svelte`

```svelte
{#await $players}
{console.log('LOADING..')}
  Loading players...
{:then result}
```
it does seem to show that `{:then }` block is unmounted and remounted whenever data is changed as @Momics explained.

I had similar issue when having a list of items that depended on an `id` variable that would change, it would flash the whole list component as it was destroyed.

I made this component to address this issue:

```svelte
<!-- Loader.svelte -->
<script>
  import { query as apolloQuery } from 'svelte-apollo'
  import { client } from '../utils/apollo'

  export let query
  export let variables = undefined
  export let initial = null

  let data = initial

  $: q = apolloQuery(client, { query, variables })

  $: (async () => {
    let result = await $q
    setData(result.data)
  })()

  function setData(d) {
    data = d
  }
</script>

{#await $q}
  <slot {data} loading={true} />
{:then q}
  <slot {data} loading={false} />
{/await}
```

Used in this way:

```svelte
 {#if $propertyId}
    <Loader
      let:data
      let:loading
      query={DASHBOARD}
      variables={{
        propertyId: Number($propertyId),
        limit,
        offset: limit * page,
        filter: $filter$ ? `%${$filter$}%` : null }}>
      {#if data}
        <table>
          ....
       
          <!-- Pagination updates data in way not shown here, but notice "loading"
          used here sort of like a simplistic useTransition(..) from React to show 
           intermediate loading state next to pagination buttons before data items update  -->
           <Pagination
              colspan={cols}
              count={data.units_aggregate.aggregate.count}
              {loading}
              bind:limit
              bind:page
              on:prev={() => (expandedRow = null)}
              on:next={() => (expandedRow = null)} /> 
        </table>
```

**Comment by frederikhors** [comment]
@cdock1029 thanks for you answer!

Your example is here (https://codesandbox.io/s/sleepy-mirzakhani-lfvkb), but it still re-renders the entire list!

😢

**Comment by frederikhors** [comment]
What do you think, guys, if we change things to make it more like @urql/svelte?

From this:

```svelte
<script>
  import { getClient, query } from 'svelte-apollo';
  import { GET_BOOKS } from './queries';

  const client = getClient();

  const books = query(client, { query: GET_BOOKS });
</script>

{#await $books}
  Loading...
{:then result}
  {#each result.data.books as book}
    {book.title} by {book.author.name}
  {/each}
{:catch error}
  Error: {error}
{/await}
```

to this:

```svelte
<script>
  import { query } from '@urql/svelte';
  import { GET_TODOS } from './queries';

  $: todos = query({
    query: GET_TODOS,
    variables: myVariables
  });
</script>

{#if $todos.fetching}
  Loading...
{:else if $todos.error}
  Oh no! {$todos.error.message}
{:else}
  <ul>
    {#each $todos.data.todos as todo}
      <li>{todo.text}</li>
    {/each}
  </ul>
{/if}
```

This can fix https://github.com/timhall/svelte-apollo/issues/19, https://github.com/timhall/svelte-apollo/issues/40 and https://github.com/timhall/svelte-apollo/issues/21.

Already started here: https://github.com/timhall/svelte-apollo/pull/42.

Can you help?

**Comment by peacememories** [comment]
This can be worked around by using a derived state like so:
```js
 const results = derived(
    standardsQuery,
    async ($query, set) => set(await $query),
    cache.data
  );
```
This version does not use `{#await}` at all, but interestingly, `{#await}` can handle non-promise values. So what could be changed is that svelte-apollo emits a promise when the query is created, and then emits raw values whenever a result is already available. this way, the waiting portion of `{#await}` would only be hit when there is actual waiting going on
