### ISSUE TITLE
Apollo 2.6 returnPartialData: true

### ISSUE THREAD

**Issue by frederikhors** [timhall/svelte-apollo#20]
**ORIGINAL ISSUE**:

With the new `returnPartialData: true` described in https://blog.apollographql.com/whats-new-in-apollo-client-2-6-b3acf28ecad1 it seems there is some problem.

<del>Using the example in home (https://github.com/timhall/svelte-apollo#query) and `returnPartialData: true` it works but renders two times the block in `{:then result}`.

<del>And if I reload directly the browser page there are the `Loading...` that remains forever like this and the `undefined` text that after the query (in background) becomes the right data.

It returns immediately the empty object `{}` so we have to check `{:then result}` blocks every time with `if`s.

**Is there a better way?**

**Reproduction**: https://codesandbox.io/s/lingering-surf-txtwv

**Comment by frederikhors** [comment]
I think using also `fetchPolicy: "cache-and-network"` fix but I'm still trying...

**Comment by frederikhors** [comment]
With `fetchPolicy: "cache-and-network` now the problem is with browser page reload. It doesn't wait. But this I think is another issue that should be opened (maybe with a repro).

**Comment by frederikhors** [comment]
I think the issue is not here. Maybe I will re-open.

**Comment by timhall** [comment]
> It returns immediately the empty object {} so we have to check {:then result} blocks every time with ifs.

It seems like that is the intended functionality of `returnPartialData`. From the release announcement that you linked:

> As long as you can make your application code resilient to the possibility of missing data...

I'll handle #21 in that issue.
