### ISSUE TITLE
any chance to implement notifyOnNetworkStatusChange on query?

### ISSUE THREAD

**Issue by michaeljoser** [timhall/svelte-apollo#22]
in react-apollo we can use "notifyOnNetworkStatusChange" in query options to refetch queries when network reconnects - any tip how we could implement that in svelte-apollo?

or any tip how we can detect network reconnect?  ( i can detect network disconnect using apollo-link-error )

thank you for the hard work !

**Comment by timhall** [comment]
You should be able to pass the `notifyOnNetworkStatusChange` option to query like this:

```html
<script>
  import { getClient, query } from 'svelte-apollo';
  import { GET_BOOKS } from './queries';

  const client = getClient();
  const books = query(client, {
    query: GET_BOOKS

    // 
    notifyOnNetworkStatusChange: true
  });
</script>

<ul>
  {#await $books}
    <li>Loading...</li>
  {:then result}
    {#if result.networkStatus === 4}
      Refetching!
    {:else}
      {#each result.data.books as book (book.id)}
        <li>{book.title} by {book.author.name}</li>
      {/each}
    {/if}
  {:catch error}
    <li>ERROR: {error}</li>
  {/await}
</ul>
```

You can see all available options here: [ApolloClient.watchQuery](https://www.apollographql.com/docs/react/api/apollo-client/#ApolloClient.watchQuery)

**Comment by shawndoyle** [comment]
I wanted to re-up this issue as this solution is not working on v0.4.  I really relied on this feature in react-apollo, so I'd love to see it in this library

Thanks for the great work!
