### ISSUE TITLE
Dynamic Parameters and Sapper

### ISSUE THREAD

**Issue by stunjiturner** [timhall/svelte-apollo#26]
i have some good working code fetching qraphql data from a external endpoint, I need a helpful example with how to use with Sapper and Dynamic Parameters, using the books example from repo, when the book tile is returned from a query, how does one get component/page that gets the actual book details, when the link is clicked on the book title using dynamic parameters/ sapper routing.

**Comment by jerriclynsjohn** [comment]
It'll be of great help if you could share the working repo @stunjiturner

**Comment by stunjiturner** [comment]
``` <!-- MembersList.svelte -->
<script>
  import { getClient, query } from 'svelte-apollo';
  import { GET_MEMBERS } from '../queries';

  // 2. Get the Apollo client from context
  const client = getClient();

  // 3. Execute the GET_BOOKS graphql query using the Apollo client
  //    -> Returns a svelte store of promises that resolve as values come in
  const members = query(client, { query: GET_MEMBERS });
</script>

<!-- 4. Use $books (note the "$"), to subscribe to query values -->
{#await $members}
  Loading...
{:then result}
  <h3 class="ui header"> Family - Team Turner </h3>
  <div class="ui list">
    {#each result.data.members as member}
      <div class="item"><a rel='prefetch' href='/member/[name].svelte'>{member.name}</a></div>
    {/each}
  </div>
{:catch error}
  Error: {error}
{/await} ```

**Comment by stunjiturner** [comment]
In my routes /member folder,  I have a a dynamic route [name].svelte. I want to call this route on the link that returns my Family Members Names from an external GRAPHQL endpoint.

**Comment by timhall** [comment]
Not sure exactly what the problem is, seems a little specific to your use-case. To follow sapper progress, see #9
