### ISSUE TITLE
apollo-cache-persist

### ISSUE THREAD

**Issue by sandman18** [timhall/svelte-apollo#32]
Hi, Can this package be used with Apollo-cache-persist?

**Comment by frederikhors** [comment]
Yes of course.

**Comment by frederikhors** [comment]
@sandman18 still having problems?

Can we close this?

**Comment by m-dary-nur** [comment]
hi , it seems not work with version 0.5.0 here s example

`export const createApolloClient = () => {
	persistCache({
		cache,
		storage: new LocalStorageWrapper(window.localStorage),
	});
	
	const client = new ApolloClient({
	/* ... */
	});
	setClient(client);
};

createApolloClient();
`

`<script>
  import { query } from "svelte-apollo";
  import { GET_BOOKS } from "./queries";

  const books = query(GET_BOOKS) // never called;
</script>

<div>{JSON.stringify($books)}</div>
`
