### ISSUE TITLE
Discussion: Hydrate client in Sapper with less boilerplate

### ISSUE THREAD

**Issue by justinmoon** [timhall/svelte-apollo#36]
The [example from the docs](https://github.com/timhall/svelte-apollo#sapper--ssr) mostly works for me:

```
<script context="module">
  ...
  export async function preload() {
    return {
      cache: await client.query({   ...   })
    }
  }
</script>

<script>
  ...
  export let cache;
  restore(client, EVERYTHING, cache.data);
  setClient(client);
  ...
</script>
...
```

But it's very tiresome to include the `restore` and `setClient` calls on every page. Is it possible to define some kind of middleware which instantiates a client-side `ApolloClient()` instance and hydrates it from `cache.data` _if the preload function returned a `cache` attribute_?

I don't know svelte / sapper well enough to know if this is possible, but it seems like it should be!

**Comment by justinmoon** [comment]
[Here's a related issue in Sapper repo](https://github.com/sveltejs/sapper/issues/751). The author made a PR that hasn't received any review in 6 months, which is concerning ...

**Comment by timhall** [comment]
Will track this in #9
