### ISSUE TITLE
Sapper progress?

### ISSUE THREAD

**Issue by matt3224** [timhall/svelte-apollo#4]
Hello Tim,

I'm looking into this as began using apollo, would be great to see sapper examples, any chance of an update?

Thanks,
Matt

**Comment by timhall** [comment]
I’m planning on updating this library for the upcoming svelte and sapper releases and will take another look then. Two things were tricky before that will need a closer look: extracting the provider cache to be passed to the client and “rehydrating” queries from preloaded data. Hoping for some progress in the next month or so.

**Comment by matt3224** [comment]
Thanks for the update Tim, it sounds promising!

**Comment by timhall** [comment]
Added some [details to the readme](https://github.com/timhall/svelte-apollo#sapper--ssr) and will update it / make sure it works once the next version of sapper is out.
