### ISSUE TITLE
Use getClient internally and use result directly (not #await)

### ISSUE THREAD

**Issue by frederikhors** [timhall/svelte-apollo#43]
@timhall, what do you think if we change things to make it more like `@urql/svelte`?

From this:

```svelte
<script>
  import { getClient, query } from 'svelte-apollo';
  import { GET_BOOKS } from './queries';

  const client = getClient();

  const books = query(client, { query: GET_BOOKS });
</script>

{#await $books}
  Loading...
{:then result}
  {#each result.data.books as book}
    {book.title} by {book.author.name}
  {/each}
{:catch error}
  Error: {error}
{/await}
```

to this:

```svelte
<script>
  import { query } from '@urql/svelte';
  import { GET_TODOS } from './queries';

  $: todos = query({ query: GET_TODOS });
</script>

{#if $todos.fetching}
  Loading...
{:else if $todos.error}
  Oh no! {$todos.error.message}
{:else}
  <ul>
    {#each $todos.data.todos as todo}
      <li>{todo.text}</li>
    {/each}
  </ul>
{/if}
```

This can fix https://github.com/timhall/svelte-apollo/issues/19, https://github.com/timhall/svelte-apollo/issues/40 and https://github.com/timhall/svelte-apollo/issues/21.

Already started here: https://github.com/timhall/svelte-apollo/pull/42 but I need help.

**Comment by roblevintennis** [comment]
First off, thank you for this library. I've been able to successfully populate a list view query, and a login query using it, and I'm really happy to have this adapter allow me to use graphql / apollo in Svelte-land! 💯 

So, I was about to create an issue apprehensively as I don't believe my issues are a bug but lack of docs perhaps--but the _not #await_ part of this ticket makes me want to add my 2 cents...

For the Svelte master of which I suspect are in the minority and most of us are using this lib while also learning Svelte at this point, perhaps this is a non-issue, but, I was trying to get to the bottom of **what's going on with Svelte with this dollar sign** exactly and why does everything stop working unless you "dereference" the result of your query or mutation result variable?

I scoured their docs and it looks like there are two general uses of `$` in Svelte:

1. reactive statements

https://svelte.dev/docs#3_$_marks_a_statement_as_reactive

But this one uses `$: foo` and, for example, in my app I have something like: `$: isListView = viewType === ViewTypes.List;` which is nicely _reactive_ such that if any of the dependencies in the conditional check change e.g. `viewType` then `isListView` will "react" and change as well. I use this to determine whether to have a toggle have "card view" or "list view" active. But, this doesn't seem to be how svelte-apollo is using dollar (I think).

2. Prefix stores

https://svelte.dev/docs#4_Prefix_stores_with_$_to_access_their_values

I'm assuming that this must be how svelte-apollo is using this idiom and what gets returned upon something like a `query`. Essentially, I'm getting some sort of Promise reference to a store e.g. `QueryStore`.

Reading the return type of `QueryStore` [here](https://github.com/timhall/svelte-apollo/blob/master/src/query.ts#L34 QueryStore<TData>) and the structure def [here](https://github.com/timhall/svelte-apollo/blob/master/src/query.ts#L61) appears to confirm this although I'm still having trouble fully grok'ing some of that.

All to say, I think some clarification on exactly what's happening here would be extremely helpful in the docs and help folks ramp up more quickly. I'm happy to help with a PR but only if I understand and can write the correct things :-)
