### ISSUE TITLE
How to update child component query when its sibling child component does a mutation?

### ISSUE THREAD

**Issue by AnnieTaylorCHEN** [timhall/svelte-apollo#54]
Hi so I have two child component **Cart** and **Orders** in parent component **App**

**Cart** have mutations with variables A, B, C. 
In the example we have :
$: books.refetch({A, B, C });
but $books query are also in the same component.
After this I want its sibling **Order** to update the orders. 

How could I communicate between them?

**Comment by timhall** [comment]
Sorry for the late reply, basically you should either store the state in the parent `App` component or if they're not direct descendants then you could use svelte's [context API](https://svelte.dev/tutorial/context-api)
