### ISSUE TITLE
Invariant Violation: Expecting a parsed GraphQL document

### ISSUE THREAD

**Issue by drejohnson** [timhall/svelte-apollo#6]
I was following the docs for using with Sapper/SSR. It seems that the `restore` function expects a query string wrapped in a `gql` but is receiving a object from the `cache` which throws an error of `Invariant Violation: Expecting a parsed GraphQL document ...`.

**Comment by timhall** [comment]
Oops, ok I'll check this out, hadn't fleshed out all the tests just yet
