### ISSUE TITLE
Error: Function called outside component initialization

### ISSUE THREAD

**Issue by albertms10** [timhall/svelte-apollo#61]
While setting up `svelte-apollo` with Sapper (#9), as there is no main `App.svelte` component, I tried to set the client in the `_layout.svelte` file.

```svelte
<!-- _layout.svelte -->
<script lang="ts">
  import { setClient } from "svelte-apollo";
  import client from "../database/apollo";

  setClient(client);
</script>
```

 However, I get the following error:

```shell
Uncaught (in promise) Error: Function called outside component initialization
    at get_current_component (index.mjs:629)
    at setContext (index.mjs:659)
    at setClient (svelte-apollo.es.js:14)
    at _layout.svelte:33
    at run (index.mjs:18)
    at Array.map (<anonymous>)
    at index.mjs:1390
    at flush (index.mjs:723)
    at init (index.mjs:1477)
    at new App (App.svelte:17)
```

Where should I set the client, instead?

### Edit

In previous versions to `v0.3.0`, the solution that https://github.com/timhall/svelte-apollo/issues/9#issuecomment-612456525 comments would work fine, but in `v0.4.0` the client must be set with the proper method.

**Comment by patrickleet** [comment]
you need to add `svelte-apollo` as a dev dependency not a dependency

**Comment by albertms10** [comment]
Whoops, totally correct. Thanks!

**Comment by patrickleet** [comment]
well, it's not exactly intuitive - I made the same mistake :)

**Comment by SamJacobs** [comment]
@patrickleet why would you add it as a dev dependency? it's part of the build right?
i did try that and it's still not fixing the problem for me, where does that fix come from?

**Comment by patrickleet** [comment]
https://github.com/sveltejs/sapper/issues/592

**Comment by patrickleet** [comment]
A bundle is created so technically most of the deps can just exist for the build step.

I saw more discussion somewhere about what should and shouldn't be a devDep with that in mind but can't find where that was.

**Comment by fnune** [comment]
I have the same problem and moving `svelte-apollo` to dev dependencies doesn't help:

```
// App.ts
<script lang="ts">
  import { ApolloClient, InMemoryCache } from "@apollo/client"
  import { setClient } from "svelte-apollo"

  setClient(new ApolloClient({ cache: new InMemoryCache() }))
</script>

<main />

<style lang="scss">
</style>
```

One special aspect of my setup is that I have a Yarn workspace and my Svelte app (built with Svelte-Kit) sits inside one of its packages. So the `node_modules` directory is on the root of the workspace, and the Svelte app has its own `node_modules` directory that contains only `.vite` and `.bin`.

**Comment by flashspys** [comment]
If svelte is built by vite, you have to add `svelte-apollo` to the `optimizeDeps.exclude` array in vite.config.js
Should this piece of information should be added in the readme?

**Comment by markusschmitz53** [comment]
> dd `svelte-apollo` to the `optimizeDeps.exclude` array in vite.config.js
> Should this piec

Unfortunately, this doesn't solve the issue at hand.
