### ISSUE TITLE
External dependency warning after upgrade to `@apollo/client`

### ISSUE THREAD

**Issue by ImCorfitz** [timhall/svelte-apollo#67]
How to configure Rollup in order to avoid this?

![Screenshot 2020-10-28 at 15 49 40](https://user-images.githubusercontent.com/52371939/97452609-351d3600-1935-11eb-9c96-e51f398bdfb6.png)

**Comment by andres-mestra** [comment]
I fixed the bug with:
```javascript
 import {ApolloClient, InMemoryCache, HttpLink,} from '@ apollo / client / core';
```

**Comment by ImCorfitz** [comment]
There we go! Easy as 𝛑! Yesterday I merged a PR  https://github.com/ImCorfitz/sapper-w-svelte-apollo/pull/7  which also did exactly this, so yeah. Awesome!
