### ISSUE TITLE
Unable to get started with v3

### ISSUE THREAD

**Issue by lunchboxer** [timhall/svelte-apollo#8]
Using a fresh svelte v3 template I was unable to get svelte-apollo working.

steps to reproduce:

```sh
npx degit sveltejs/template#v3 svelte-apollo-v3-test
cd svelte-apollo-v3-test
npm i svelte-apollo@next apollo-boost graphql-tag graphql
```

then my app looks like this:

```html
<!-- App.svelte -->
<Semesters />

<script>
  import ApolloClient from 'apollo-boost';  
  import { setClient } from 'svelte-apollo';
  import Semesters from './Semesters.svelte';

  const client = new ApolloClient({ uri: 'http://localhost:4000' });
  setClient(client);
</script>

<!-- Semesters.svelte -->
<script>
  import { getClient, query } from 'svelte-apollo'; 
  import { GET_SEMESTERS } from './queries';

  const client = getClient();
  const semesters = query(client, { query: GET_SEMESTERS });
</script>

{#await semesters}
  Loading...
{:then result}
  {#each result.data.semesters as semester}
    {semester.name}
  {/each}
{:catch error}
  Error: {error}
{/await}

<!-- queries.js -->
import gql from 'graphql-tag'

export const GET_SEMESTERS = gql`
{
  semesters {
    id
    name
  }
}
`
```
Then run `npm run dev` which doesn't complain. Open the app in the browser to get the following error in Chrome:

```
Uncaught ReferenceError: process is not defined
    at new t (bundle.esm.js:45)
    at Lo (App.svelte:8)
    at S (internal.mjs:1361)
    at new target (main.js:3)
    at main.js:3
    at main.js:6
```

Any clues as to how I can get this working?

**Comment by lunchboxer** [comment]
Also, it may be worth noting that the app described above is nearly identical to the example in the README of this repo.

**Comment by lunchboxer** [comment]
I spent a fair amount of time on this yesterday, but submitting the issue helped me to think about the problem more clearly. This was a problem with the rollup config with the svelte template in current v3. I was able to fix it with: 

```
import replace from "rollup-plugin-replace";

...
export default {
...
plugins: [
    replace({
      'process.env.NODE_ENV': JSON.stringify( 'production' )
    }),
...
  ]
...
}
```

**Comment by frederikhors** [comment]
@lunchboxer I think this is a not good work-around for the problem. Can we reopen this please?

**Comment by timhall** [comment]
It appears that as of Apollo 2.4, `process.env.NODE_ENV` needs to be defined, see https://github.com/apollographql/apollo-client/issues/4665. `JSON.stringify('production') === `"production"` works fine or you could `JSON.stringify(process.env.NODE_ENV)` to pass through the environment's value
