### ISSUE TITLE
Is this repo dead?

### ISSUE THREAD

**Issue by jan-musi** [timhall/svelte-apollo#94]
Thank you, @timhall, for making this helpful tool! :)

Are you still maintaining this repository? I ask because no commits have been made in 6 months, despite the 15 open issues (14 unresponded) and 9 open pull requests (all unresponded).

**Comment by timhall** [comment]
Not dead, just dormant while I work on some different projects
![6BBF5B02-7099-4308-96AA-59459C30D651](https://user-images.githubusercontent.com/1211148/119919378-529c9780-bf38-11eb-9e10-3de7bcb73502.jpeg)

**Comment by jan-musi** [comment]
@timhall Do you want to add me as a contributor? I would be happy to merge the security-vulnerability-related Dependabot PRs, as well as any simple community-submitted improvement PRs.
